---
# This starts a local image store serve metal-hammer develop purpose.
# it also echo´s metal-hammer rest calls to make them succeed and visible.
version: '3'
services:
  imagestore:
    image: nginx:latest
    ports:
      - "4711:80"
    volumes:
      - .:/usr/share/nginx/html:ro
  echoserver:
    image: mendhak/http-https-echo
    ports:
      - "4712:80"

