name: Mainline Build

on:
  push:
    branches:
    # Restriction will be removed once the build in the test branch is finished
      - test-github-actions

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  images:
    name: Build OS
    strategy:
      matrix:
        os: [debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare build environment
      shell: bash
      run: |
        ./prepare.sh ${{ matrix.os }}
        mkdir -p images/test
        touch images/test/test
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '278.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Testupload to GCS
      run: gsutil cp -r ./images/ gs://$GCS_BUCKET
    - name: Build docker image for workers and export tarball
      uses: metal-stack/action-docker-make@master
      with:
        args: >
          --work-dir debian
          --file docker-make.${{ matrix.os }}.yaml
          --no-cache
          --no-push
          --summary
          --no-lint
    - name: Build docker image for firewalls and export tarball
      uses: metal-stack/action-docker-make@master
      with:
        args: >
          --work-dir firewall
          --build-only ${{ matrix.os }}
          --no-cache
          --no-push
          --no-pull
          --summary
          --no-lint
    - name: List directory
      shell: bash
      run: ls -alhR .
    - name: Upload image tarballs to GCS
      uses: peter-evans/s3-backup@v1.0.1
      with:
        args: --overwrite 
