name: Mainline Build

on:
  push:
    branches:
    # Restriction will be removed once the build in the test branch is finished
      - test-github-actions

env:
  STORAGE_SERVICE_ALIAS: gcs
  STORAGE_SERVICE_URL: https://storage.googleapis.com
  ACCESS_KEY_ID: ${{ secrets.GCS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.GCS_SECRET_ACCESS_KEY }}
  MIRROR_SOURCE: images/
  MIRROR_TARGET: images.metal-pod.io

jobs:
  images:
    name: Build OS
    strategy:
      matrix:
        os: [debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh ${{ matrix.os }}
    - name: Build docker image for workers and export tarball
      uses: metal-stack/action-docker-make@master
      with:
        args: >
          --work-dir debian
          --file docker-make.${{ matrix.os }}.yaml
          --no-cache
          --no-push
          --summary
          --no-lint
    - name: Build docker image for firewalls and export tarball
      uses: metal-stack/action-docker-make@master
      with:
        args: >
          --work-dir firewall
          --build-only ${{ matrix.os }}
          --no-cache
          --no-push
          --no-pull
          --summary
          --no-lint
    - name: Upload image tarballs to GCS
      uses: peter-evans/s3-backup@v1.0.1
      with:
        args: --overwrite 
