name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GCS_BUCKET: images.metal-pod.io
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  debian-ubuntu:
    name: Build Debian and Ubuntu based OS images

    strategy:
      matrix:
        os:
        - name: debian
          version: 12
        - name: ubuntu
          version: 24.04

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: metal-stack
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Go 1.25
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
        cache: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        args: --build-tags integration --timeout=3m

    - name: build install
      run: make

    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh ${{ matrix.os.name }}
      env:
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}

    - name: use our lz4 which is version 1.10 with multithread support
      shell: bash
      run: |
        chmod +x test/lz4
        sudo cp test/lz4 /usr/bin/lz4

    - name: Build docker image for workers
      uses: docker/bake-action@v6
      with:
        source: .
        files: ./docker-bake.hcl
        targets: ${{ matrix.os.name }}
        no-cache: true
      env:
        OS_NAME: ${{ matrix.os.name }}
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}
        SEMVER_PATCH: -${{ github.head_ref }}

    - name: Test and export docker image for workers
      run: |
        ./test.sh ghcr.io/metal-stack/${OS_NAME}:${SEMVER_MAJOR_MINOR}${SEMVER_PATCH}
        ./export.sh
      env:
        CIS_VERSION: v4.1-4
        IMG_PKG_COMMAND: dpkg -l
        OS_NAME: ${{ matrix.os.name }}
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}
        SEMVER_PATCH: -${{ github.head_ref }}

    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh firewall
      env:
        SEMVER_MAJOR_MINOR: 3.0-ubuntu
      if: ${{ matrix.os.name == 'ubuntu' }}

    - name: Build docker image for firewalls
      uses: docker/bake-action@v6
      with:
        source: .
        files: ./docker-bake.hcl
        targets: ubuntu-firewall
        no-cache: true
      env:
        OS_NAME: firewall
        SEMVER_MAJOR_MINOR: 3.0-ubuntu
        SEMVER_PATCH: -${{ github.head_ref }}
      if: ${{ matrix.os.name == 'ubuntu' }}

    # TODO enable debian build again, actually droptailer and firewall-controller did not get enabled
    # and then goss tests fail
    - name: Test and export docker image for firewalls
      run: |
        ./test.sh ghcr.io/metal-stack/firewall:${SEMVER_MAJOR_MINOR}${SEMVER_PATCH}
        ./export.sh
      env:
        IMG_PKG_COMMAND: dpkg -l
        OS_NAME: firewall
        SEMVER_MAJOR_MINOR: 3.0-ubuntu
        SEMVER_PATCH: -${{ github.head_ref }}
      if: ${{ matrix.os.name == 'ubuntu' }}

    - name: Build docker image for capms
      uses: docker/bake-action@v6
      with:
        source: .
        files: ./docker-bake.hcl
        targets: ubuntu-capms
        no-cache: true
      env:
        KUBE_VERSION: 1.34.1
        KUBE_APT_BRANCH: v1.34
        OS_NAME: capms
        SEMVER_MAJOR_MINOR: 1.34.1
        SEMVER_PATCH: -${{ github.head_ref }}
      if: ${{ matrix.os.name == 'ubuntu' }}

    - name: Test and export docker image for capms
      run: |
        ./test.sh ghcr.io/metal-stack/capms:${SEMVER_MAJOR_MINOR}-ubuntu-24.04${SEMVER_PATCH}
        ./export.sh
      env:
        IMG_PKG_COMMAND: dpkg -l
        OS_NAME: capms
        SEMVER_MAJOR_MINOR: 1.34.1
        SEMVER_PATCH: -${{ github.head_ref }}
        UBUNTU_VERSION: -ubuntu-24.04
      if: ${{ matrix.os.name == 'ubuntu' }}

    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh debian-nvidia
      env:
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}
      if: ${{ matrix.os.name == 'debian' }}

    - name: Build docker image for debian-nvidia
      uses: docker/bake-action@v6
      with:
        source: .
        files: ./docker-bake.hcl
        targets: debian-nvidia
        no-cache: true
      env:
        OS_NAME: debian-nvidia
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}
        SEMVER_PATCH: -${{ github.head_ref }}
      if: ${{ matrix.os.name == 'debian' }}

    - name: Test and export docker image for debian-nvidia based workers
      run: |
        ./export.sh
      env:
        IMG_PKG_COMMAND: dpkg -l
        OS_NAME: debian-nvidia
        SEMVER_MAJOR_MINOR: ${{ matrix.os.version }}
        SEMVER_PATCH: -${{ github.head_ref }}
      if: ${{ matrix.os.name == 'debian' }}

    - name: Upload image tarballs to GCS
      run: cd images && gsutil -m -h "Cache-Control:no-store" cp -r . gs://$GCS_BUCKET/metal-os/pull_requests/

  almalinux:
    name: Build Almalinux based OS image
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: metal-stack
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Go 1.25
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'
        cache: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build install
      run: make
    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh almalinux
      env:
        SEMVER_MAJOR_MINOR: 9

    - name: Build image
      uses: docker/bake-action@v6
      with:
        source: .
        files: ./docker-bake.hcl
        targets: almalinux
        no-cache: true
      env:
        OS_NAME: almalinux
        SEMVER_MAJOR_MINOR: 9
        SEMVER_PATCH: -${{ github.head_ref }}

    - name: Test and export docker image for almalinux based workers
      run: |
        ./test.sh ghcr.io/metal-stack/${OS_NAME}:${SEMVER_MAJOR_MINOR}${SEMVER_PATCH}
        ./export.sh
      env:
        IMG_PKG_COMMAND: rpm -qa
        OS_NAME: almalinux
        SEMVER_MAJOR_MINOR: 9
        SEMVER_PATCH: -${{ github.head_ref }}

    - uses: google-github-actions/setup-gcloud@v0
      with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Upload image tarballs to GCS
      run: cd images && gsutil -m -h "Cache-Control:no-store" cp -r . gs://$GCS_BUCKET/metal-os/pull_requests/

