name: Pipeline

on:
  pull_request:
    branches:
      - master

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  debian-ubuntu:
    name: Build Debian and Ubuntu based OS images
    strategy:
      matrix:
        os: [debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh ${{ matrix.os }}
    - name: Build docker image for workers and export tarball
      uses: metal-stack/action-docker-make@move-to-docker-make-docker-image
      with:
        args: >
          --work-dir debian
          --file docker-make.${{ matrix.os }}.yaml
          --no-cache
          --summary
          --no-lint
          --no-push
          --log-level DEBUG
  #   - name: Build docker image for firewalls and export tarball
  #     run: |
  #       DOCKER_MAKE_REGISTRY_LOGIN_USER="metalstack+ci" \
  #       DOCKER_MAKE_REGISTRY_LOGIN_PASSWORD="${{ secrets.QUAY_IO_TOKEN }}" \
  #       TMPDIR=/var/tmp \
  #       docker-make \
  #         --work-dir firewall \
  #         --build-only ${{ matrix.os }} \
  #         --no-cache \
  #         --no-pull \
  #         --summary \
  #         --no-lint \
  #         --no-push
  #   - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #     with:
  #         version: '278.0.0'
  #         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #   - name: Upload image tarballs to GCS
  #     run: cd images && gsutil -m cp -r . gs://$GCS_BUCKET/metal-os/pull_requests/
  # centos:
  #   name: Build Centos based OS image
  #   runs-on: self-hosted
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: Prepare build environment
  #     shell: bash
  #     run: ./prepare.sh centos
  #   - name: Build docker image for centos based workers and export tarball
  #     run: |
  #       DOCKER_MAKE_REGISTRY_LOGIN_USER="metalstack+ci" \
  #       DOCKER_MAKE_REGISTRY_LOGIN_PASSWORD="${{ secrets.QUAY_IO_TOKEN }}" \
  #       TMPDIR=/var/tmp \
  #       docker-make \
  #         --work-dir centos \
  #         --file docker-make.yaml \
  #         --no-cache \
  #         --no-push \
  #         --summary \
  #         --no-lint \
  #         --no-push
  #   - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #     with:
  #         version: '278.0.0'
  #         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #   - name: Upload image tarballs to GCS
  #     run: cd images && gsutil -m cp -r . gs://$GCS_BUCKET/metal-os/pull_requests/
