name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - master

env:
  GCS_BUCKET: images.metal-pod.io
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  cluster-api:
    name: Build Ubuntu based OS image for Cluster API

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --build-tags integration -p bugs -p unused --timeout=3m

    - name: build install
      run: make

    - name: Prepare build environment
      shell: bash
      run: ./prepare.sh ubuntu

    - name: use our lz4 which is version 1.10 with multithread support
      shell: bash
      run: |
        chmod +x test/lz4
        sudo cp test/lz4 /usr/bin/lz4

    - name: Build docker image for workers and export tarball
      run: |
        DOCKER_MAKE_REGISTRY_LOGIN_USER="metalstack+ci" \
        DOCKER_MAKE_REGISTRY_LOGIN_PASSWORD="${{ secrets.QUAY_IO_TOKEN }}" \
        TMPDIR=/var/tmp \
        docker-make \
          --work-dir debian \
          --file docker-make.ubuntu.yaml \
          --no-cache \
          --summary \
          --no-lint \
          --no-push

    - name: Build docker image for cluster api images and export tarball
      run: |
        TMPDIR=/var/tmp \
        docker-make \
          --work-dir cluster-api \
          --file docker-make.yaml \
          --no-cache \
          --no-pull \
          --summary \
          --no-lint \
          --no-push

    - name: Upload image tarballs to GCS
      run: cd images && gsutil -m -h "Cache-Control:no-store" cp -r . gs://$GCS_BUCKET/metal-os/pull_requests/
