---
name: Release Drafter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # we now update the draft with a download table:
    # this is basically done for testing that the udpate on a release works

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'

    - name: Get release
      id: get_release
      uses: agners/get-draft-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - run: |
        PREFIX=metal-os/stable go run ./cmd/tools/generate-table > downloads.md

    - name: Update release body
      id: update_release
      uses: tubone24/update_release@v1.3.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
        RELEASE_ID: ${{ steps.get_release.outputs.id }}
      with:
        draft: true
        body_path: ./downloads.md
        is_append_body: true
