---
name: Release Drafter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'

    - run: |
        # this is basically done for testing that the release update works before a release
        PREFIX=metal-os/stable go run ./cmd/tools/generate-table > downloads.md

    - name: Update release body
      id: update_release
      uses: tubone24/update_release@v1.3.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: true
        body_path: ./downloads.md
        is_append_body: true
